### ISSUE TITLE
compiling error on Ubuntu 18.04

### ISSUE THREAD

**Issue by lvclark** [pblischak/polyploid-genotyping#3]
Hi Paul,
I tried installing EBG on our machine running Ubuntu 18.04.  When I ran `make`, I got the error "'isnan' was not declared in this scope", as well as suggestions to use `std::isnan`.
Lindsay

**Comment by pblischak** [comment]
Hi Lindsay -- thanks for letting me know about this! I will try fixing this bug later today.

**Comment by lvclark** [comment]
Thanks for the fix!  It compiles now and seems to be running fine for me.
